const prompt=require("prompt-sync")();
let ran=Math.random()*100
ran=Number.parseInt(ran)
let i=0
let inp
console.log("This is a Game in which a random number is generated by the system.")
console.log("You are required to guess the number using hints that would be provided as required.")
console.log("Try doing it in as less number of tries as you can.")
do
{
    inp=prompt("Enter a Number between 1 and 100 : ")
    inp=Number.parseInt(inp)
    if(ran==inp)
    {
        console.log("Both are Equal.")
    }
    else if(ran>inp)
    {
        console.log("Enter a Greater Number.")
    }
    else if(ran<inp)
    {
        console.log("Enter a Smaller Number.")
    }
    i+=1
}
while(inp!=ran)
console.log()
console.log("The Random Number is : " , ran)
console.log("The Entered Number is : " , inp)
console.log("Number of tries : ", i)