/*This is a Simple Leisure time Guess The Number game build using Java */

import java.util.Scanner;

public class GuessTheNumber 
{
    public static void main(String[] args)
    {
        int ran,guess,tries=0;
        Scanner sc=new Scanner(System.in);
        ran=(int)(Math.random()*100);
        System.out.println();
        System.out.println("This is a Game in which a Random Number is generated by the System.");
        System.out.println();
        System.out.println("You are required to guess the number using HINTS that would be provided as required.");
        System.out.println();
        System.out.println("Try doing it in as less number of Tries as you can.");
        System.out.println("-------------------------------------------------------------------------------------");
        System.out.println();
        System.out.println("Guess a Number between 0 and 100 .");
        do
        {
            guess=sc.nextInt();
            if(guess>ran)
            {
                System.out.println("Wrong Guess...");
                System.out.println("[HINT] Enter a Smaller Number : ");
            }
            else if(guess<ran)
            {
                System.out.println("Wrong Guess...");
                System.out.println("[HINT] Enter a Greater Number : ");
            } 
            tries+=1;
        }
        while(guess!=ran);
        System.out.println("You have Guessed \""+ran+"\" correctly in "+tries+" tries.");
        sc.close();
    }
}
