/*This is a Simple Leisure time Guess The Number game build using Java */

import java.util.Scanner;
import java.util.Random;
class Game
{
    Scanner sc=new Scanner(System.in);
    private int random;
    private int n;
    public Game()
    {
        Random ran=new Random();
        random=ran.nextInt(100);
    }
    public int userInput()
    {
        n=sc.nextInt();
        return n;
    }
    public boolean isCorrectNumber()
    {
        if(n==random)
        {
            return true;
        }
        return false;
    }
    public int getn()
    {
        return n;
    }
    public int getrandom()
    {
        return random;
    }
}

public class GuessTheNumber
{
    public static void main(String[] args) 
    {
        System.out.println("This is a Game in which a random number is generated by the system.");
        System.out.println("You are required to guess the number using hints.");
        System.out.println("You only have 10 chances to win.");
        System.out.println("______________________________________________________________________");
        System.out.println("Now, Enter a Number between 0 and 100: ");
        Game player=new Game();
        int random=player.getrandom();
        int count=0;
        do
        {
            player.userInput();
            ++count;
            int n=player.getn();
            if(player.isCorrectNumber())
            {
                System.out.print("You won and your score is "+(10-count));
                System.exit(0);
            }
            else if(player.isCorrectNumber()==false)
            {
                if(n>random)
                {
                    System.out.println("Uh ho! Try again with a Smaller Number");
                }
                else if(n<random)
                {
                    System.out.println("Uh ho! Try again with a Greater Number");
                }
            }
        }
        while(count<10);
        System.out.println("Game Over ! You have Exceeded the Number of Tries.");
    }
}
